name: CI with F2FS Support

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker with F2FS support
      run: |
        docker run --privileged -d --name f2fs_container ubuntu:latest sleep infinity
        docker exec f2fs_container apt-get update
        docker exec f2fs_container apt-get install -y f2fs-tools
        docker exec f2fs_container modprobe f2fs
        
    - name: Create and mount F2FS filesystem inside Docker
      run: |
        docker exec f2fs_container truncate -s 100M f2fs.img
        docker exec f2fs_container mkfs.f2fs f2fs.img
        docker exec f2fs_container mkdir -p /mnt/f2fs_test
        docker exec f2fs_container mount -t f2fs f2fs.img /mnt/f2fs_test

    - name: Run tests on F2FS inside Docker
      run: |
        docker exec f2fs_container # Your test commands here

    - name: Cleanup
      if: always()
      run: |
        docker exec f2fs_container umount /mnt/f2fs_test
        docker stop f2fs_container
        docker rm f2fs_container
